---
- hosts: "tag_testnet_{{ netname }}"
  strategy: free
  gather_facts: yes
  tasks:
    - name: Create .aws directory
      file:
        path: ~/.aws
        state: directory
        mode: '0755'

    - name: Copy your aws creds
      copy:
        src: ~/.aws/credentials
        dest: ~/.aws/credentials
        owner: admin
        group: admin
        mode: '0400'

    - name: Sync Logs
      shell: |
        testnet=$(cat /etc/testnet_config.json | jq -r .testnet)
        aws s3 sync ${HOME} s3://crashlogs.o1test.net/${testnet}/{{ ansible_date_time.date }}/{{ ansible_hostname }}/  --exclude "*" --include "test-*" > aws.log

    - name: Remove .aws
      file:
        path: ~/.aws
        state: absent